buildpack: https://github.com/pkgr/pkgr-noop-buildpack.git
cli: docker-gc
default_dependencies: false
before:
  - mkdir -p packaging bin
  - mv docker-gc bin/
  - echo '0 5 * * * root FORCE_IMAGE_REMOVAL=1 FORCE_CONTAINER_REMOVAL=1 /usr/bin/docker-gc' > packaging/docker-gc-cron
targets:
  ubuntu-16.04: true
  ubuntu-14.04: true
  debian-7: true
  debian-8: true
  centos-7: true
  sles-12: true
crons:
  - packaging/docker-gc-cron
