buildpack: https://github.com/pkgr/pkgr-noop-buildpack.git
cli: docker-gc
default_dependencies: false
before:
  - mkdir -p packaging bin
  - mv docker-gc bin/
  - echo '0 * * * * root /usr/bin/docker-gc' > packaging/docker-gc-cron
targets:
  ubuntu-16.04: true
crons:
  - packaging/docker-gc-cron
